openapi: 3.0.0
info:
  title: simple-api
  version: 0.1.0
x-kusk:
  cors:
    origins:
      - "*"
    methods:
      - GET
      - POST
  mocking: 
    enabled: true
  # upstream:
  #   service:
  #     name: hello-world-svc
  #     namespace: default
  #     port: 8080
  # openapi-path: openapi.yaml
  # rate_limit:
  #   requests_per_unit: 2
  #   unit: minute
  # cache:
  #   enabled: true
  #   max_age: 60
  # auth:
  #   scheme: basic
  #   auth-upstream:
  #     host:
  #       hostname: basic-auth-svc.default
  #       port: 8080
paths:
  /hello:
    get:
      responses:
        "200":
          description: A simple hello world!
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Hello from a mocked response!
  /validated:
    # x-kusk:
    #   validation: 
    #     request:
    #       enabled: true
    post:
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              required:
                - name
              type: object
              properties:
                name:
                  type: string
      responses:
        "200":
          description: ""
          content:
            text/plain:
              schema:
                type: string
              example: Hello mocked Kusk!
