openapi: 3.0.0
servers: 
  - url: http://localhost:8080 
info:
  title: simple-api
  version: 0.1.0
  description: A simple API example to test Kusk Gateway with
  license: 
    name: MIT
    url: https://github.com/kubeshop/kusk-gateway/blob/main/LICENSE
x-kusk:
  cors:
    origins:
      - "*"
    methods:
      - GET
      - POST
  upstream:
    service: 
      name: hello-world-svc
      namespace: default
      port: 8080
paths:
  /hello:
    get:
      summary: Returns a Hello world to the user
      responses:
        "200":
          description: A simple hello world!
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: Hello from a mocked response!
  /validated:
    # x-kusk:
    #   validation: 
    #     request:
    #       enabled: true
    post:
      summary: Given a name, it returns a greeting
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              required:
                - name
              type: object
              properties:
                name:
                  type: string
      responses:
        "200":
          description: ""
          content:
            text/plain:
              schema:
                type: string
              example: Hello mocked Kusk!
