apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-cert
  namespace: default
spec:
  dnsNames:
    - api.aabedraba.com
  secretName: api.aabedraba.com
  issuerRef:
    name: letsencrypt-prod