apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-cert
  namespace: default
spec:
  dnsNames:
    - oauth-demo.aabedraba.com
  secretName: oauth-demo.aabedraba.com
  issuerRef:
    name: letsencrypt-prod